/**
 * Everything here is derived from `lib/bindings/supabase.ts` — generated by
 * `supabase gen types typescript` against the live `calls`/`call_utterances`
 * table schema (see ferry/migration), not hand-maintained.
 *
 * The camelCase list/detail shapes below exist because screens expect
 * camelCase while Postgres columns are snake_case — but every field's type
 * is pulled from the generated row type, so a column rename or an enum
 * value change breaks the build here instead of drifting silently.
 */
import type { Tables } from "@/lib/bindings/supabase";

export type CallRow = Tables<"calls">;
export type CallUtteranceRow = Tables<"call_utterances">;

export type CallDirection = CallRow["direction"];
export type CallLifecycleStatus = CallRow["status"];
export type CallEndReason = NonNullable<CallRow["end_reason"]>;
export enum Speaker {
  Caller = "caller",
  Callee = "callee",
}

export interface CallListItem {
  id: CallRow["id"];
  fromNumber: CallRow["from_number"];
  toNumber: CallRow["to_number"];
  /** What "call again" dials. Null once the agent is deleted, while
   * `agentName` survives as the history snapshot. */
  agentId: CallRow["agent_id"];
  agentName: CallRow["agent_name"];
  inputLanguage: CallRow["input_language"];
  outputLanguage: CallRow["output_language"];
  endReason: CallRow["end_reason"];
  billableSeconds: CallRow["billable_seconds"];
  createdAt: CallRow["created_at"];
}

export interface Utterance {
  seq: CallUtteranceRow["seq"];
  speaker: CallUtteranceRow["speaker"];
  originalText: CallUtteranceRow["original_text"];
  originalLanguage: CallUtteranceRow["original_language"];
  translatedText: CallUtteranceRow["translated_text"];
  translatedLanguage: CallUtteranceRow["translated_language"];
  /** This turn's span in the *original* recording (`CallDetail.recordingUrl`) —
   * each party's own voice. */
  offsetMs: CallUtteranceRow["offset_ms"];
  durationMs: CallUtteranceRow["duration_ms"];
  /** This turn's span in the *translated* recording
   * (`CallDetail.translatedRecordingUrl`) instead — only ever set on the
   * other party's turns, since the call owner's own turns sit in that same
   * recording at `offsetMs`/`durationMs`, unmodified. */
  translatedOffsetMs: CallUtteranceRow["translated_offset_ms"];
  translatedDurationMs: CallUtteranceRow["translated_duration_ms"];
}

/** Everything the list deliberately leaves out, plus the transcript. */
export interface CallDetail {
  id: CallRow["id"];
  direction: CallRow["direction"];
  fromNumber: CallRow["from_number"];
  toNumber: CallRow["to_number"];
  agentId: CallRow["agent_id"];
  agentName: CallRow["agent_name"];
  inputLanguage: CallRow["input_language"];
  outputLanguage: CallRow["output_language"];
  status: CallRow["status"];
  endReason: CallRow["end_reason"];
  error: CallRow["error"];
  createdAt: CallRow["created_at"];
  ringingAt: CallRow["ringing_at"];
  connectedAt: CallRow["connected_at"];
  endedAt: CallRow["ended_at"];
  billableSeconds: CallRow["billable_seconds"];
  costMicros: CallRow["cost_micros"];
  /** Each party's own voice, unmodified — null until the call has ended
   * and the recording finished uploading. */
  recordingUrl: CallRow["recording_url"];
  /** What this call's owner actually heard live: their own voice, plus the
   * TTS translation of the other party. Same lifecycle as `recordingUrl`. */
  translatedRecordingUrl: CallRow["translated_recording_url"];
  utterances: Utterance[];
}

export enum RecordingVariant {
  Original = "original",
  Translated = "translated",
}

/**
 * Where this turn sits in the given recording, in milliseconds. For
 * `Translated`, the call owner's own turns (`caller`) keep the same span as
 * the original recording — their own voice is unmodified there too — only
 * the other party's turns (`callee`) get the translated-track numbers.
 */
export function turnSpan(
  utterance: Utterance,
  variant: RecordingVariant,
): { offsetMs: number | null; durationMs: number | null } {
  if (
    variant === RecordingVariant.Translated &&
    utterance.speaker === Speaker.Callee
  ) {
    return {
      offsetMs: utterance.translatedOffsetMs,
      durationMs: utterance.translatedDurationMs,
    };
  }
  return { offsetMs: utterance.offsetMs, durationMs: utterance.durationMs };
}

export interface RecentCallsResponse {
  calls: CallListItem[];
  /** Feed back as `before` for the next page. `null` means this was the
   * last page — distinct from an empty page, which the client would
   * otherwise have to guess at. */
  nextBefore: string | null;
}
