/**
 * Everything here is derived from `lib/bindings/supabase.ts` — generated by
 * `supabase gen types typescript` against the live `calls`/`call_utterances`
 * table schema (see ferry/migration), not hand-maintained.
 *
 * The camelCase list/detail shapes below exist because screens expect
 * camelCase while Postgres columns are snake_case — but every field's type
 * is pulled from the generated row type, so a column rename or an enum
 * value change breaks the build here instead of drifting silently.
 */
import type { Tables } from "@/lib/bindings/supabase";

export type CallRow = Tables<"calls">;
export type CallUtteranceRow = Tables<"call_utterances">;

export type CallDirection = CallRow["direction"];
export type CallLifecycleStatus = CallRow["status"];
export type CallEndReason = NonNullable<CallRow["end_reason"]>;
export type Speaker = CallUtteranceRow["speaker"];

export interface CallListItem {
  id: CallRow["id"];
  fromNumber: CallRow["from_number"];
  toNumber: CallRow["to_number"];
  /** What "call again" dials. Null once the agent is deleted, while
   * `agentName` survives as the history snapshot. */
  agentId: CallRow["agent_id"];
  agentName: CallRow["agent_name"];
  inputLanguage: CallRow["input_language"];
  outputLanguage: CallRow["output_language"];
  endReason: CallRow["end_reason"];
  billableSeconds: CallRow["billable_seconds"];
  createdAt: CallRow["created_at"];
}

export interface Utterance {
  seq: CallUtteranceRow["seq"];
  speaker: CallUtteranceRow["speaker"];
  originalText: CallUtteranceRow["original_text"];
  originalLanguage: CallUtteranceRow["original_language"];
  translatedText: CallUtteranceRow["translated_text"];
  translatedLanguage: CallUtteranceRow["translated_language"];
  offsetMs: CallUtteranceRow["offset_ms"];
  durationMs: CallUtteranceRow["duration_ms"];
}

/** Everything the list deliberately leaves out, plus the transcript. */
export interface CallDetail {
  id: CallRow["id"];
  direction: CallRow["direction"];
  fromNumber: CallRow["from_number"];
  toNumber: CallRow["to_number"];
  agentId: CallRow["agent_id"];
  agentName: CallRow["agent_name"];
  inputLanguage: CallRow["input_language"];
  outputLanguage: CallRow["output_language"];
  status: CallRow["status"];
  endReason: CallRow["end_reason"];
  error: CallRow["error"];
  createdAt: CallRow["created_at"];
  ringingAt: CallRow["ringing_at"];
  connectedAt: CallRow["connected_at"];
  endedAt: CallRow["ended_at"];
  billableSeconds: CallRow["billable_seconds"];
  costMicros: CallRow["cost_micros"];
  recordingUrl: CallRow["recording_url"];
  utterances: Utterance[];
}

export interface RecentCallsResponse {
  calls: CallListItem[];
  /** Feed back as `before` for the next page. `null` means this was the
   * last page — distinct from an empty page, which the client would
   * otherwise have to guess at. */
  nextBefore: string | null;
}
