// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gender } from "./Gender";
import type { Language } from "./Language";
import type { Mode } from "./Mode";

export type AgentResponse = { id: string, name: string, inputLanguage: Language, outputLanguage: Language, mode: Mode, gender: Gender, mascot: string, voice: string, };
