// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiError } from "./ApiError";

/**
 * The envelope every ferry route returns. Generic, so the generated
 * TypeScript is generic too and the client keeps its payload type.
 */
export type ApiResponse<T> = { statusCode: number, data?: T, error?: ApiError, };
