// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";
import type { EndReason } from "./EndReason";
import type { Language } from "./Language";
import type { Status } from "./Status";
import type { UtteranceResponse } from "./UtteranceResponse";

/**
 * Everything the list deliberately leaves out, plus the transcript.
 */
export type CallDetailResponse = { id: string, direction: Direction, fromNumber: string, toNumber: string,
/**
 * Null once the agent is deleted, while `agent_name` survives — the
 * snapshot is what history renders, this is only for "open this agent".
 */
agentId: string | null, agentName: string | null, inputLanguage: Language | null, outputLanguage: Language | null, status: Status, endReason: EndReason | null, error: string | null, createdAt: string, ringingAt: string | null,
/**
 * The anchor every `offset_ms` below is measured from.
 */
connectedAt: string | null, endedAt: string | null, billableSeconds: number,
/**
 * `number`, not ts-rs's default `bigint` for i64: JSON.parse yields a
 * number, so the generated type would be lying about the runtime value.
 * Safe here — INR micros only exceed Number.MAX_SAFE_INTEGER past ~9
 * billion rupees on a single call.
 */
costMicros: number, recordingUrl: string | null, utterances: Array<UtteranceResponse>, };
