// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndReason } from "./EndReason";
import type { Language } from "./Language";

export type CallListItemResponse = { id: string, fromNumber: string, toNumber: string, agentName: string | null, inputLanguage: Language | null, outputLanguage: Language | null,
/**
 * The call's real terminal state. Deriving a display "outcome" from it
 * is the client's job — storing one would let the two drift.
 */
endReason: EndReason | null, billableSeconds: number, createdAt: string, };
