// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of usage a `Charge` entry billed. Needed because not every
 * billable session has a `calls` row to point `call_id` at — try-agent
 * (see `http::handlers::try_agent`) is a one-way demo with its own
 * `call_id` that is never written to `calls`, so `call_type` is what tells
 * a try-agent charge apart from a real phone call once `call_id` is null
 * for both. Null for non-charge entries (topup, refund, bonus, adjustment).
 */
export type CallType = "phone_call" | "try_agent";
