// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallType } from "./CallType";
import type { EntryType } from "./EntryType";
import type { Language } from "./Language";

/**
 * One row (or one call's worth of rows, summed) in Credits History. What
 * used to be `lib/credits/api.ts`'s `getCreditHistory` doing this grouping
 * client-side in JS, now done once in SQL: PostgREST has no GROUP BY, and
 * grouping in JS meant fetching every underlying stt/mt/tts row over the
 * wire just to collapse them again on-device.
 */
export type CreditHistoryEntryResponse = {
/**
 * `call:<call_id>` for a grouped call/session summary, the ledger row's
 * own id otherwise — same scheme the client used to build itself.
 */
id: string, entryType: EntryType, callType: CallType | null, isCallSummary: boolean, amountCredits: number, agentName: string | null, inputLanguage: Language | null, outputLanguage: Language | null,
/**
 * Raw `BillingObserver` note ("stt"/"mt"/"tts") for a standalone charge
 * row; null for a grouped summary or any non-charge entry — display
 * labels live client-side (`lib/credits/format.ts`), not here.
 */
stage: string | null, createdAt: string, };
