// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreditHistoryEntryResponse } from "./CreditHistoryEntryResponse";

export type CreditHistoryResponse = { entries: Array<CreditHistoryEntryResponse>,
/**
 * Pass back as `before` to fetch the next page; null once this was the
 * last one — same contract as `RecentCallsResponse::nextBefore`.
 */
nextBefore: string | null, };
