// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EndReason = "busy" | "no_answer" | "failed" | "hung_up_by_a" | "hung_up_by_b";
