// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What moved the balance. `Charge` and `call_type` are set together — every
 * other variant is not call-shaped (a topup, a promo grant, a manual fix)
 * and leaves both `call_type` and `call_id` null.
 */
export type EntryType = "charge" | "topup" | "refund" | "bonus" | "adjustment";
