// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreviewVoiceResponse = {
/**
 * Base64-encoded WAV audio — Sarvam's REST endpoint returns WAV by
 * default, so no re-encoding is needed on this side.
 */
audioBase64: string, };
