// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallListItemResponse } from "./CallListItemResponse";

export type RecentCallsResponse = { calls: Array<CallListItemResponse>,
/**
 * Feed back as `before` for the next page. `None` means this was the
 * last page — distinct from an empty page, which the client would
 * otherwise have to guess at.
 */
nextBefore: string | null, };
