// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Just enough to draw one row: the avatar, the title, and the line of
 * history under it. The agent's configuration — languages, mode, gender,
 * voice — is deliberately absent; `GET /v1/agents/{id}` is what the row
 * taps through to, and sending it here would mean sending three agents'
 * full configuration to render nine words.
 */
export type RecentAgentResponse = { id: string, name: string, mascot: string,
/**
 * The most recent call this agent handled — what "recently used" orders
 * by, and the only reason the calls table is joined at all.
 */
lastUsedAt: string,
/**
 * `number`, not ts-rs's default `bigint` for i64: COUNT is i64 in
 * Postgres, but this is one user's calls to one agent, so it is a
 * JavaScript number long before it is anything else.
 */
callCount: number, };
