// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The two people on the call. The agent is never a speaker — it does not
 * originate a turn, it re-voices one, and its output is `translated_text` on
 * whichever speaker's row it translated.
 */
export type Speaker = "caller" | "callee";
