// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The one-way demo's offer. Distinct from `call::WebrtcOfferRequest`, which
 * is the two-leg flow and additionally carries `to_number` — they were both
 * called `WebrtcOffer*` while having different shapes.
 */
export type TryAgentOfferRequest = { offerSdp: string, agentId: string, };
