// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gender } from "./Gender";
import type { Language } from "./Language";
import type { Mode } from "./Mode";

/**
 * Partial update — every field is optional and, when omitted from the
 * request body entirely, leaves that column untouched. All of `agents`'
 * columns are NOT NULL, so there's no separate "clear it back to null"
 * state to represent — a plain `Option<T>` (omitted vs. present) covers
 * this fully, unlike the double-Option tri-state a nullable column needs.
 */
export type UpdateAgentRequest = { name?: string, inputLanguage?: Language, outputLanguage?: Language, mode?: Mode, gender?: Gender, mascot?: string, voice?: string, };
