// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Language } from "./Language";
import type { Speaker } from "./Speaker";

/**
 * One line of the conversation. Original and translation share a row because
 * one spoken turn is one chat bubble: `speaker` picks the side, the two text
 * fields pick the language.
 */
export type UtteranceResponse = { seq: number, speaker: Speaker, originalText: string, originalLanguage: Language | null, translatedText: string | null, translatedLanguage: Language | null,
/**
 * Milliseconds from `connected_at` — where this line sits in the
 * recording, and how long it runs.
 */
offsetMs: number | null, durationMs: number | null, };
