import { CallOutcome, type CallRowItem } from "@/components/CallRow";

/** Recent calls per agent id, most recent first. */
export const AGENT_CALLS: Record<string, CallRowItem[]> = {
  "1": [
    {
      id: "a1-1",
      name: "Priya Sharma",
      number: "+91 98765 43210",
      fromNumber: "+1 888 799 9666",
      agent: "Front Desk",
      language: "Hindi → English",
      duration: "2:15",
      outcome: CallOutcome.Resolved,
      time: "3 hours ago",
    },
    {
      id: "a1-2",
      name: "Arjun Mehta",
      number: "+91 91234 56780",
      fromNumber: "+1 888 799 9667",
      agent: "Front Desk",
      language: "Hindi → English",
      duration: "1:04",
      outcome: CallOutcome.Transferred,
      time: "6 hours ago",
    },
    {
      id: "a1-3",
      name: "Divya Rao",
      number: "+91 99887 66554",
      fromNumber: "+1 888 799 9666",
      agent: "Front Desk",
      language: "Telugu → English",
      duration: "0:48",
      outcome: CallOutcome.Missed,
      time: "1 day ago",
    },
    {
      id: "a1-4",
      name: "Ramesh Iyer",
      number: "+91 90123 45678",
      fromNumber: "+1 888 799 9666",
      agent: "Front Desk",
      language: "Tamil → English",
      duration: "3:22",
      outcome: CallOutcome.Resolved,
      time: "2 days ago",
    },
  ],
  "2": [
    {
      id: "a2-1",
      name: "Priya Sharma",
      number: "+91 98765 43210",
      fromNumber: "+1 888 799 9668",
      agent: "Billing",
      language: "Hindi → English",
      duration: "4:01",
      outcome: CallOutcome.Transferred,
      time: "2 weeks ago",
    },
    {
      id: "a2-2",
      name: "Karthik Nair",
      number: "+91 97765 44321",
      fromNumber: "+1 888 799 9668",
      agent: "Billing",
      language: "Kannada → English",
      duration: "2:40",
      outcome: CallOutcome.Resolved,
      time: "3 weeks ago",
    },
  ],
  "3": [
    {
      id: "a3-1",
      name: "Sneha Kulkarni",
      number: "+91 90011 22334",
      fromNumber: "+1 888 799 9669",
      agent: "Order Status",
      language: "Hindi → English",
      duration: "1:02",
      outcome: CallOutcome.Missed,
      time: "1 month ago",
    },
  ],
  "4": [],
  "5": [],
};
