import { CallOutcome, type CallRowItem } from "@/components/CallRow";

/** Recent calls per phone number id, most recent first. */
export const NUMBER_CALLS: Record<string, CallRowItem[]> = {
  "1": [
    {
      id: "n1-1",
      name: "Priya Sharma",
      number: "+91 98765 43210",
      fromNumber: "+1 415 555 0132",
      agent: "Front Desk",
      language: "Hindi → English",
      duration: "2:15",
      outcome: CallOutcome.Resolved,
      time: "3 hours ago",
    },
    {
      id: "n1-2",
      name: "Arjun Mehta",
      number: "+91 91234 56780",
      fromNumber: "+1 415 555 0132",
      agent: "Front Desk",
      language: "Hindi → English",
      duration: "1:04",
      outcome: CallOutcome.Transferred,
      time: "6 hours ago",
    },
    {
      id: "n1-3",
      name: "Divya Rao",
      number: "+91 99887 66554",
      fromNumber: "+1 415 555 0132",
      agent: "Front Desk",
      language: "Telugu → English",
      duration: "0:48",
      outcome: CallOutcome.Missed,
      time: "1 day ago",
    },
  ],
  "2": [
    {
      id: "n2-1",
      name: "Karthik Nair",
      number: "+91 97765 44321",
      fromNumber: "+91 80 4567 8901",
      agent: "Billing",
      language: "Kannada → English",
      duration: "2:40",
      outcome: CallOutcome.Resolved,
      time: "1 day ago",
    },
    {
      id: "n2-2",
      name: "Priya Sharma",
      number: "+91 98765 43210",
      fromNumber: "+91 80 4567 8901",
      agent: "Billing",
      language: "Hindi → English",
      duration: "4:01",
      outcome: CallOutcome.Transferred,
      time: "2 weeks ago",
    },
  ],
  "3": [
    {
      id: "n3-1",
      name: "Sneha Kulkarni",
      number: "+91 90011 22334",
      fromNumber: "+1 888 555 0187",
      agent: "Order Status",
      language: "Hindi → English",
      duration: "1:02",
      outcome: CallOutcome.Missed,
      time: "1 month ago",
    },
  ],
  "4": [],
  "5": [],
};
