[package]
name = "ferry"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
base64 = "0.22"
async-trait = "0.1"
axum = { version = "0.8.9", features = ["ws"] }
dotenvy = "0.15"
futures-util = "0.3"
jsonwebtoken = "9"
nnnoiseless = "0.5"
ort = { version = "2.0.0-rc.13", default-features = false, features = ["download-binaries", "tls-rustls"] }
percent-encoding = "2"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json", "stream"] }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.53.1", features = ["full"] }
tokio-tungstenite = { version = "0.24", features = ["rustls-tls-webpki-roots"] }
tower-http = { version = "0.6", features = ["trace", "cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
    "ansi",
    "std",
    "smallvec",
    "env-filter",
    "json",
] }
nu-ansi-term = "0.50"
rubato = { version = "5.0.0", features = ["fft_resampler"] }
audioadapter-buffers = "5.1.0"
webrtc = "0.20.2"
bytes = "1.12.1"
validator = { version = "0.19", features = ["derive"] }
uuid = { version = "1", features = ["serde", "v4"] }
regex = "1"
sqlx = { version = "0.8", default-features = false, features = [
    "runtime-tokio",
    "tls-rustls-ring-webpki",
    "postgres",
    "macros",
    "uuid",
    "json",
] }

[profile.dev]
debug = 1
