// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const cloneTemplateAgent = `-- name: CloneTemplateAgent :one
insert into
  agents (org_id, name, mascot, purpose, created_by)
select
  app.current_org_id (),
  $1,
  t.mascot,
  t.purpose,
  app.current_user_id ()
from
  agents t
where
  t.id = $2
  and t.is_template
returning
  id
`

type CloneTemplateAgentParams struct {
	Name       string `json:"name"`
	TemplateID string `json:"templateId"`
}

// The identity of the new agent, taken from the template. org_id and created_by
// come from the session, so the row lands in the caller's org however the
// template is owned — and is_template stays false, which agents_write requires.
func (q *Queries) CloneTemplateAgent(ctx context.Context, arg CloneTemplateAgentParams) (string, error) {
	row := q.db.QueryRow(ctx, cloneTemplateAgent, arg.Name, arg.TemplateID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const cloneTemplateTools = `-- name: CloneTemplateTools :exec
insert into
  agent_tools (
    agent_id,
    org_id,
    kind,
    name,
    description,
    trigger,
    enabled,
    position,
    config,
    created_by
  )
select
  $1,
  app.current_org_id (),
  tool.kind,
  tool.name,
  tool.description,
  tool.trigger,
  tool.enabled,
  tool.position,
  tool.config,
  app.current_user_id ()
from
  agent_tools tool
  join agents t on t.id = tool.agent_id
where
  tool.agent_id = $2
  and t.is_template
`

type CloneTemplateToolsParams struct {
	AgentID    string `json:"agentId"`
	TemplateID string `json:"templateId"`
}

// Tools hang off the agent rather than the version, so they are copied once.
// Nothing is carried over from the template's own row — created_by and the
// timestamps are the caller's, because this is a new tool, not a shared one.
func (q *Queries) CloneTemplateTools(ctx context.Context, arg CloneTemplateToolsParams) error {
	_, err := q.db.Exec(ctx, cloneTemplateTools, arg.AgentID, arg.TemplateID)
	return err
}

const cloneTemplateVersion = `-- name: CloneTemplateVersion :exec
insert into
  agent_versions (
    agent_id,
    org_id,
    version,
    state,
    created_by,
    greeting,
    instructions,
    tts_provider,
    tts_model,
    voice,
    speed,
    pitch,
    llm_provider,
    llm_model,
    creativity,
    knowledge_only,
    stt_provider,
    stt_model,
    interruptible,
    reply_delay,
    noise_filter,
    switch_language,
    languages,
    starting_language,
    switch_after,
    indic_numerals,
    background_sound,
    background_volume,
    nudge_quiet_callers,
    hangup_after_nudges,
    leave_voicemail,
    voicemail_message,
    max_call_minutes,
    system_tools
  )
select
  $1,
  app.current_org_id (),
  1,
  'draft',
  app.current_user_id (),
  v.greeting,
  v.instructions,
  v.tts_provider,
  v.tts_model,
  v.voice,
  v.speed,
  v.pitch,
  v.llm_provider,
  v.llm_model,
  v.creativity,
  v.knowledge_only,
  v.stt_provider,
  v.stt_model,
  v.interruptible,
  v.reply_delay,
  v.noise_filter,
  v.switch_language,
  v.languages,
  v.starting_language,
  v.switch_after,
  v.indic_numerals,
  v.background_sound,
  v.background_volume,
  v.nudge_quiet_callers,
  v.hangup_after_nudges,
  v.leave_voicemail,
  v.voicemail_message,
  v.max_call_minutes,
  v.system_tools
from
  agents t
  join lateral (
    select
      id, agent_id, org_id, version, state, greeting, instructions, tts_provider, tts_model, voice, speed, pitch, llm_provider, llm_model, creativity, knowledge_only, stt_provider, stt_model, interruptible, reply_delay, noise_filter, switch_language, languages, starting_language, switch_after, indic_numerals, background_sound, background_volume, nudge_quiet_callers, hangup_after_nudges, leave_voicemail, voicemail_message, max_call_minutes, system_tools, created_by, created_at, updated_at
    from
      agent_versions
    where
      agent_id = t.id
    order by
      version desc
    limit
      1
  ) v on true
where
  t.id = $2
  and t.is_template
`

type CloneTemplateVersionParams struct {
	AgentID    string `json:"agentId"`
	TemplateID string `json:"templateId"`
}

// Every setting the template carries, copied into a v1 draft so the builder
// opens on something editable. A committed version would leave the new agent
// with nothing to write into.
//
// Column by column rather than `select *`: a new setting should fail to compile
// here rather than silently stop being copied.
func (q *Queries) CloneTemplateVersion(ctx context.Context, arg CloneTemplateVersionParams) error {
	_, err := q.db.Exec(ctx, cloneTemplateVersion, arg.AgentID, arg.TemplateID)
	return err
}

const createAgent = `-- name: CreateAgent :one
insert into
  agents (org_id, name, mascot, created_by)
values
  (
    app.current_org_id (),
    $1,
    nullif($2::text, ''),
    app.current_user_id ()
  )
returning
  id
`

type CreateAgentParams struct {
	Name   string `json:"name"`
	Mascot string `json:"mascot"`
}

// org_id and created_by come from the session Postgres already has, rather than
// from the token: the policy checks against those regardless.
func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (string, error) {
	row := q.db.QueryRow(ctx, createAgent, arg.Name, arg.Mascot)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createFirstVersion = `-- name: CreateFirstVersion :exec
insert into
  agent_versions (agent_id, org_id, version, state, created_by)
values
  (
    $1,
    app.current_org_id (),
    1,
    'draft',
    app.current_user_id ()
  )
`

// A new agent arrives with an empty v1 draft, so the builder always has a
// version to write settings into.
func (q *Queries) CreateFirstVersion(ctx context.Context, agentID string) error {
	_, err := q.db.Exec(ctx, createFirstVersion, agentID)
	return err
}

const freeAgentName = `-- name: FreeAgentName :one
select
  c.candidate::text as name
from
  generate_series(1, 50) as n
  cross join lateral (
    select
      case
        when n = 1 then $1::text
        else $1::text || ' ' || n::text
      end as candidate
  ) c
where
  not exists (
    select
      1
    from
      my_agents a
    where
      a.name = c.candidate
  )
order by
  n
limit
  1
`

// "Appointment management", then "Appointment management 2". Taking a template
// twice is ordinary — the second one cannot fail on the unique (org_id, name).
//
// Ordered by n rather than by the name, or "… 10" would be picked before "… 2".
func (q *Queries) FreeAgentName(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRow(ctx, freeAgentName, name)
	var name_2 string
	err := row.Scan(&name_2)
	return name_2, err
}

const getAgent = `-- name: GetAgent :one
select
  a.id,
  a.name,
  a.mascot,
  a.purpose,
  a.status,
  coalesce(a.live_version_id::text, '')::text as live_version_id,
  a.created_at,
  v.id as version_id,
  v.version,
  v.state,
  v.greeting,
  v.instructions,
  v.tts_provider,
  v.tts_model,
  v.voice,
  v.speed,
  v.pitch,
  v.llm_provider,
  v.llm_model,
  v.creativity,
  v.knowledge_only,
  v.stt_provider,
  v.stt_model,
  v.interruptible,
  v.reply_delay,
  v.noise_filter,
  v.switch_language,
  v.languages,
  v.starting_language,
  v.switch_after,
  v.indic_numerals,
  v.background_sound,
  v.background_volume,
  v.nudge_quiet_callers,
  v.hangup_after_nudges,
  v.leave_voicemail,
  v.voicemail_message,
  v.max_call_minutes,
  v.system_tools,
  v.updated_at as edited_at
from
  agents a
  join lateral (
    select
      id, agent_id, org_id, version, state, greeting, instructions, tts_provider, tts_model, voice, speed, pitch, llm_provider, llm_model, creativity, knowledge_only, stt_provider, stt_model, interruptible, reply_delay, noise_filter, switch_language, languages, starting_language, switch_after, indic_numerals, background_sound, background_volume, nudge_quiet_callers, hangup_after_nudges, leave_voicemail, voicemail_message, max_call_minutes, system_tools, created_by, created_at, updated_at
    from
      agent_versions
    where
      agent_id = a.id
      and (
        $1::int is null
        or version = $1::int
      )
    order by
      version desc
    limit
      1
  ) v on true
where
  a.id = $2
`

type GetAgentParams struct {
	Version *int32 `json:"version"`
	ID      string `json:"id"`
}

type GetAgentRow struct {
	ID                string             `json:"id"`
	Name              string             `json:"name"`
	Mascot            *string            `json:"mascot"`
	Purpose           string             `json:"purpose"`
	Status            AgentStatus        `json:"status"`
	LiveVersionID     string             `json:"liveVersionId"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	VersionID         string             `json:"versionId"`
	Version           int32              `json:"version"`
	State             VersionState       `json:"state"`
	Greeting          string             `json:"greeting"`
	Instructions      string             `json:"instructions"`
	TtsProvider       string             `json:"ttsProvider"`
	TtsModel          string             `json:"ttsModel"`
	Voice             string             `json:"voice"`
	Speed             float32            `json:"speed"`
	Pitch             float32            `json:"pitch"`
	LlmProvider       string             `json:"llmProvider"`
	LlmModel          string             `json:"llmModel"`
	Creativity        float32            `json:"creativity"`
	KnowledgeOnly     bool               `json:"knowledgeOnly"`
	SttProvider       string             `json:"sttProvider"`
	SttModel          string             `json:"sttModel"`
	Interruptible     bool               `json:"interruptible"`
	ReplyDelay        float32            `json:"replyDelay"`
	NoiseFilter       bool               `json:"noiseFilter"`
	SwitchLanguage    bool               `json:"switchLanguage"`
	Languages         []string           `json:"languages"`
	StartingLanguage  string             `json:"startingLanguage"`
	SwitchAfter       int32              `json:"switchAfter"`
	IndicNumerals     bool               `json:"indicNumerals"`
	BackgroundSound   string             `json:"backgroundSound"`
	BackgroundVolume  float32            `json:"backgroundVolume"`
	NudgeQuietCallers bool               `json:"nudgeQuietCallers"`
	HangupAfterNudges bool               `json:"hangupAfterNudges"`
	LeaveVoicemail    bool               `json:"leaveVoicemail"`
	VoicemailMessage  string             `json:"voicemailMessage"`
	MaxCallMinutes    int32              `json:"maxCallMinutes"`
	SystemTools       []string           `json:"systemTools"`
	EditedAt          pgtype.Timestamptz `json:"editedAt"`
}

// An agent at one version: identity, plus every setting that version holds.
// Without a version it takes the newest, which is what the builder wants the
// first time it opens an agent.
func (q *Queries) GetAgent(ctx context.Context, arg GetAgentParams) (GetAgentRow, error) {
	row := q.db.QueryRow(ctx, getAgent, arg.Version, arg.ID)
	var i GetAgentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mascot,
		&i.Purpose,
		&i.Status,
		&i.LiveVersionID,
		&i.CreatedAt,
		&i.VersionID,
		&i.Version,
		&i.State,
		&i.Greeting,
		&i.Instructions,
		&i.TtsProvider,
		&i.TtsModel,
		&i.Voice,
		&i.Speed,
		&i.Pitch,
		&i.LlmProvider,
		&i.LlmModel,
		&i.Creativity,
		&i.KnowledgeOnly,
		&i.SttProvider,
		&i.SttModel,
		&i.Interruptible,
		&i.ReplyDelay,
		&i.NoiseFilter,
		&i.SwitchLanguage,
		&i.Languages,
		&i.StartingLanguage,
		&i.SwitchAfter,
		&i.IndicNumerals,
		&i.BackgroundSound,
		&i.BackgroundVolume,
		&i.NudgeQuietCallers,
		&i.HangupAfterNudges,
		&i.LeaveVoicemail,
		&i.VoicemailMessage,
		&i.MaxCallMinutes,
		&i.SystemTools,
		&i.EditedAt,
	)
	return i, err
}

const getTemplateName = `-- name: GetTemplateName :one
select
  name
from
  agents
where
  id = $1
  and is_template
`

// The name a clone starts from, and the check that the id names a template at
// all. `is_template` matters: without it this would read any agent the read
// policy lets through, which includes every agent in the caller's own org.
func (q *Queries) GetTemplateName(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getTemplateName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listAgentTemplates = `-- name: ListAgentTemplates :many
select
  id,
  name,
  purpose,
  mascot,
  coalesce(template_category, '')::text as category
from
  agents
where
  is_template
order by
  template_category,
  name
`

type ListAgentTemplatesRow struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Purpose  string  `json:"purpose"`
	Mascot   *string `json:"mascot"`
	Category string  `json:"category"`
}

// The roster on the agents page. No org filter: agents_read lets templates
// through for everyone, which is the point of them.
func (q *Queries) ListAgentTemplates(ctx context.Context) ([]ListAgentTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listAgentTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentTemplatesRow{}
	for rows.Next() {
		var i ListAgentTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Purpose,
			&i.Mascot,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentTools = `-- name: ListAgentTools :many
select
  id,
  kind,
  name,
  description,
  trigger,
  enabled,
  position,
  config,
  updated_at
from
  agent_tools
where
  agent_id = $1
order by
  position,
  created_at
`

type ListAgentToolsRow struct {
	ID          string             `json:"id"`
	Kind        ToolKind           `json:"kind"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Trigger     ToolTrigger        `json:"trigger"`
	Enabled     bool               `json:"enabled"`
	Position    int32              `json:"position"`
	Config      json.RawMessage    `json:"config"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

// Tools belong to the agent rather than the version, so the list is the same
// whichever version you are looking at.
func (q *Queries) ListAgentTools(ctx context.Context, agentID string) ([]ListAgentToolsRow, error) {
	rows, err := q.db.Query(ctx, listAgentTools, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentToolsRow{}
	for rows.Next() {
		var i ListAgentToolsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Description,
			&i.Trigger,
			&i.Enabled,
			&i.Position,
			&i.Config,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
select
  a.id,
  a.name,
  a.mascot,
  a.purpose,
  a.status,
  v.updated_at as edited_at,
  -- Coalesced because the left join is null once the person who last edited it
  -- has left the org, and the cast alone would tell sqlc it never is.
  coalesce(u.email::text, '') as edited_by
from
  -- The view, not the table: agents_read lets templates through on purpose, so
  -- selecting from agents here would put the roster on everyone's board.
  my_agents a
  join lateral (
    select
      updated_at,
      created_by
    from
      agent_versions
    where
      agent_id = a.id
    order by
      version desc
    limit
      1
  ) v on true
  left join users u on u.id = v.created_by
order by
  v.updated_at desc
`

type ListAgentsRow struct {
	ID       string             `json:"id"`
	Name     string             `json:"name"`
	Mascot   *string            `json:"mascot"`
	Purpose  string             `json:"purpose"`
	Status   AgentStatus        `json:"status"`
	EditedAt pgtype.Timestamptz `json:"editedAt"`
	EditedBy interface{}        `json:"editedBy"`
}

// One row per board line. The lateral takes each agent's newest version, which
// the (agent_id, version desc) index answers without sorting.
func (q *Queries) ListAgents(ctx context.Context) ([]ListAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsRow{}
	for rows.Next() {
		var i ListAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mascot,
			&i.Purpose,
			&i.Status,
			&i.EditedAt,
			&i.EditedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
