// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgent = `-- name: CreateAgent :one
insert into
  agents (org_id, name, mascot, created_by)
values
  (
    app.current_org_id (),
    $1,
    nullif($2::text, ''),
    app.current_user_id ()
  )
returning
  id
`

type CreateAgentParams struct {
	Name   string `json:"name"`
	Mascot string `json:"mascot"`
}

// org_id and created_by come from the session Postgres already has, rather than
// from the token: the policy checks against those regardless.
func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (string, error) {
	row := q.db.QueryRow(ctx, createAgent, arg.Name, arg.Mascot)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createFirstVersion = `-- name: CreateFirstVersion :exec
insert into
  agent_versions (agent_id, org_id, version, state, created_by)
values
  (
    $1,
    app.current_org_id (),
    1,
    'draft',
    app.current_user_id ()
  )
`

// A new agent arrives with an empty v1 draft, so the builder always has a
// version to write settings into.
func (q *Queries) CreateFirstVersion(ctx context.Context, agentID string) error {
	_, err := q.db.Exec(ctx, createFirstVersion, agentID)
	return err
}

const listAgents = `-- name: ListAgents :many
select
  a.id,
  a.name,
  a.mascot,
  a.purpose,
  a.status,
  v.updated_at as edited_at,
  -- Coalesced because the left join is null once the person who last edited it
  -- has left the org, and the cast alone would tell sqlc it never is.
  coalesce(u.email::text, '') as edited_by
from
  agents a
  join lateral (
    select
      updated_at,
      created_by
    from
      agent_versions
    where
      agent_id = a.id
    order by
      version desc
    limit
      1
  ) v on true
  left join users u on u.id = v.created_by
order by
  v.updated_at desc
`

type ListAgentsRow struct {
	ID       string             `json:"id"`
	Name     string             `json:"name"`
	Mascot   *string            `json:"mascot"`
	Purpose  string             `json:"purpose"`
	Status   AgentStatus        `json:"status"`
	EditedAt pgtype.Timestamptz `json:"editedAt"`
	EditedBy interface{}        `json:"editedBy"`
}

// One row per board line. The lateral takes each agent's newest version, which
// the (agent_id, version desc) index answers without sorting.
func (q *Queries) ListAgents(ctx context.Context) ([]ListAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsRow{}
	for rows.Next() {
		var i ListAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mascot,
			&i.Purpose,
			&i.Status,
			&i.EditedAt,
			&i.EditedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
