// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AgentStatus string

const (
	AgentStatusDraft AgentStatus = "draft"
	AgentStatusLive  AgentStatus = "live"
)

func (e *AgentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentStatus(s)
	case string:
		*e = AgentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentStatus: %T", src)
	}
	return nil
}

type NullAgentStatus struct {
	AgentStatus AgentStatus `json:"agentStatus"`
	Valid       bool        `json:"valid"` // Valid is true if AgentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AgentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentStatus), nil
}

type MemberRole string

const (
	MemberRoleOwner  MemberRole = "owner"
	MemberRoleAdmin  MemberRole = "admin"
	MemberRoleMember MemberRole = "member"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole `json:"memberRole"`
	Valid      bool       `json:"valid"` // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type ToolKind string

const (
	ToolKindApi       ToolKind = "api"
	ToolKindValidator ToolKind = "validator"
	ToolKindMock      ToolKind = "mock"
)

func (e *ToolKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ToolKind(s)
	case string:
		*e = ToolKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ToolKind: %T", src)
	}
	return nil
}

type NullToolKind struct {
	ToolKind ToolKind `json:"toolKind"`
	Valid    bool     `json:"valid"` // Valid is true if ToolKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullToolKind) Scan(value interface{}) error {
	if value == nil {
		ns.ToolKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ToolKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullToolKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ToolKind), nil
}

type ToolTrigger string

const (
	ToolTriggerStart  ToolTrigger = "start"
	ToolTriggerDuring ToolTrigger = "during"
	ToolTriggerEnd    ToolTrigger = "end"
)

func (e *ToolTrigger) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ToolTrigger(s)
	case string:
		*e = ToolTrigger(s)
	default:
		return fmt.Errorf("unsupported scan type for ToolTrigger: %T", src)
	}
	return nil
}

type NullToolTrigger struct {
	ToolTrigger ToolTrigger `json:"toolTrigger"`
	Valid       bool        `json:"valid"` // Valid is true if ToolTrigger is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullToolTrigger) Scan(value interface{}) error {
	if value == nil {
		ns.ToolTrigger, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ToolTrigger.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullToolTrigger) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ToolTrigger), nil
}

type VersionState string

const (
	VersionStateDraft     VersionState = "draft"
	VersionStateCommitted VersionState = "committed"
)

func (e *VersionState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VersionState(s)
	case string:
		*e = VersionState(s)
	default:
		return fmt.Errorf("unsupported scan type for VersionState: %T", src)
	}
	return nil
}

type NullVersionState struct {
	VersionState VersionState `json:"versionState"`
	Valid        bool         `json:"valid"` // Valid is true if VersionState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVersionState) Scan(value interface{}) error {
	if value == nil {
		ns.VersionState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VersionState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVersionState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VersionState), nil
}

type Agent struct {
	ID               string             `json:"id"`
	OrgID            string             `json:"orgId"`
	Name             string             `json:"name"`
	Mascot           *string            `json:"mascot"`
	Purpose          string             `json:"purpose"`
	Status           AgentStatus        `json:"status"`
	LiveVersionID    pgtype.UUID        `json:"liveVersionId"`
	CreatedBy        pgtype.UUID        `json:"createdBy"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
	IsTemplate       bool               `json:"isTemplate"`
	TemplateCategory *string            `json:"templateCategory"`
}

type AgentTool struct {
	ID          string             `json:"id"`
	AgentID     string             `json:"agentId"`
	OrgID       string             `json:"orgId"`
	Kind        ToolKind           `json:"kind"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Trigger     ToolTrigger        `json:"trigger"`
	Enabled     bool               `json:"enabled"`
	Position    int32              `json:"position"`
	Config      json.RawMessage    `json:"config"`
	CreatedBy   pgtype.UUID        `json:"createdBy"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type AgentVersion struct {
	ID                string             `json:"id"`
	AgentID           string             `json:"agentId"`
	OrgID             string             `json:"orgId"`
	Version           int32              `json:"version"`
	State             VersionState       `json:"state"`
	Greeting          string             `json:"greeting"`
	Instructions      string             `json:"instructions"`
	TtsProvider       string             `json:"ttsProvider"`
	TtsModel          string             `json:"ttsModel"`
	Voice             string             `json:"voice"`
	Speed             float32            `json:"speed"`
	Pitch             float32            `json:"pitch"`
	LlmProvider       string             `json:"llmProvider"`
	LlmModel          string             `json:"llmModel"`
	Creativity        float32            `json:"creativity"`
	KnowledgeOnly     bool               `json:"knowledgeOnly"`
	SttProvider       string             `json:"sttProvider"`
	SttModel          string             `json:"sttModel"`
	Interruptible     bool               `json:"interruptible"`
	ReplyDelay        float32            `json:"replyDelay"`
	NoiseFilter       bool               `json:"noiseFilter"`
	SwitchLanguage    bool               `json:"switchLanguage"`
	Languages         []string           `json:"languages"`
	StartingLanguage  string             `json:"startingLanguage"`
	SwitchAfter       int32              `json:"switchAfter"`
	IndicNumerals     bool               `json:"indicNumerals"`
	BackgroundSound   string             `json:"backgroundSound"`
	BackgroundVolume  float32            `json:"backgroundVolume"`
	NudgeQuietCallers bool               `json:"nudgeQuietCallers"`
	HangupAfterNudges bool               `json:"hangupAfterNudges"`
	LeaveVoicemail    bool               `json:"leaveVoicemail"`
	VoicemailMessage  string             `json:"voicemailMessage"`
	MaxCallMinutes    int32              `json:"maxCallMinutes"`
	SystemTools       []string           `json:"systemTools"`
	CreatedBy         pgtype.UUID        `json:"createdBy"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
}

type MyAgent struct {
	ID               string             `json:"id"`
	OrgID            string             `json:"orgId"`
	Name             string             `json:"name"`
	Mascot           *string            `json:"mascot"`
	Purpose          string             `json:"purpose"`
	Status           AgentStatus        `json:"status"`
	LiveVersionID    pgtype.UUID        `json:"liveVersionId"`
	CreatedBy        pgtype.UUID        `json:"createdBy"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
	IsTemplate       bool               `json:"isTemplate"`
	TemplateCategory *string            `json:"templateCategory"`
}

type Org struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type User struct {
	ID           string             `json:"id"`
	OrgID        string             `json:"orgId"`
	Email        string             `json:"email"`
	Phone        string             `json:"phone"`
	Name         string             `json:"name"`
	Role         MemberRole         `json:"role"`
	PasswordHash string             `json:"passwordHash"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
}
