/**
 * Everything here is derived from `lib/bindings/supabase.ts` — generated by
 * `supabase gen types typescript` against the live `agents` table schema
 * (see ferry/migration), not hand-maintained. `RecentAgent` still comes
 * from ferry's `get_recent_agents` (a join+aggregate PostgREST can't
 * express) via ts-rs.
 *
 * The camelCase request/response shapes below exist because screens expect
 * camelCase while Postgres columns are snake_case — but every field's type
 * is pulled from the generated row type, so a column rename or an enum
 * value change breaks the build here instead of drifting silently.
 */
import type {
  Tables,
  TablesInsert,
  TablesUpdate,
} from "@/lib/bindings/supabase";

export type { RecentAgentResponse as RecentAgent } from "@/lib/bindings/RecentAgentResponse";
export type { PreviewVoiceResponse } from "@/lib/bindings/PreviewVoiceResponse";

export type AgentRow = Tables<"agents">;
export type AgentInsertRow = TablesInsert<"agents">;
export type AgentUpdateRow = TablesUpdate<"agents">;

export type Language = AgentRow["input_language"];
export type Mode = AgentRow["mode"];
export type Gender = AgentRow["gender"];

export interface AgentResponse {
  id: AgentRow["id"];
  name: AgentRow["name"];
  inputLanguage: AgentRow["input_language"];
  outputLanguage: AgentRow["output_language"];
  mode: AgentRow["mode"];
  gender: AgentRow["gender"];
  mascot: AgentRow["mascot"];
  voice: AgentRow["voice"];
}

export interface CreateAgentRequest {
  name: AgentInsertRow["name"];
  inputLanguage: AgentInsertRow["input_language"];
  outputLanguage: AgentInsertRow["output_language"];
  mode: AgentInsertRow["mode"];
  gender: AgentInsertRow["gender"];
  mascot: AgentInsertRow["mascot"];
  voice: AgentInsertRow["voice"];
}

/** Every field optional — an omitted key leaves that column untouched,
 * matching a PostgREST PATCH's partial-update semantics. */
export interface UpdateAgentRequest {
  name?: AgentUpdateRow["name"];
  inputLanguage?: AgentUpdateRow["input_language"];
  outputLanguage?: AgentUpdateRow["output_language"];
  mode?: AgentUpdateRow["mode"];
  gender?: AgentUpdateRow["gender"];
  mascot?: AgentUpdateRow["mascot"];
  voice?: AgentUpdateRow["voice"];
}
