/**
 * Derived from `lib/bindings/supabase.ts` — generated by
 * `supabase gen types typescript` against the live `credit_balances`/
 * `credit_ledger` tables (see
 * ferry/migration/src/m20260904_000000_create_credit_tables.rs), not
 * hand-maintained.
 */
import type { Tables } from "@/lib/bindings/supabase";

export type CreditBalanceRow = Tables<"credit_balances">;
export type CreditLedgerRow = Tables<"credit_ledger">;

export type CreditEntryType = CreditLedgerRow["entry_type"];
export type CreditCallType = NonNullable<CreditLedgerRow["call_type"]>;

export interface CreditBalance {
  /** Never negative in practice, but not clamped here — a real negative
   * balance (a charge that landed after the pre-flight check already let a
   * call start) is meaningful and should surface, not be hidden. */
  remaining: number;
  updatedAt: string;
}

/**
 * One line in the credits history list. Not always one `credit_ledger` row:
 * `BillingObserver` writes a separate row per usage stage (STT, MT, TTS),
 * not one per call, so every charge sharing a `call_id` is summed into a
 * single `isCallSummary` entry here — the same way a phone bill shows one
 * line per call, not one per second. A try-agent charge has no `call_id` to
 * group by at all (see `BillingObserver`'s `call_type` handling), so it
 * surfaces as its own per-stage row; that's a real limit of today's schema,
 * not a client-side choice.
 */
export interface CreditHistoryEntry {
  /** `call:<call_id>` for a summed call entry, the ledger row's own id
   * otherwise — stable and unique either way. */
  id: string;
  entryType: CreditEntryType;
  callType: CreditCallType | null;
  isCallSummary: boolean;
  amountCredits: number;
  /** Only set on a phone-call summary — joined from `calls`, the snapshot
   * taken at call time (see `calls.agent_name`). */
  agentName: string | null;
  /** Only set on a phone-call summary. */
  language: string | null;
  /** The usage stage this one row billed ("stt" | "mt" | "tts"), only
   * meaningful on a standalone charge row — once several stages are summed
   * into a call summary, no single stage describes it anymore. */
  stage: string | null;
  createdAt: string;
}
